### ISSUE TITLE
Launch daemon

### ISSUE THREAD

**Issue by fuzzycheck** [grahamgilbert/puppet-puppet_run#1]
Hi,
   install.pp creates a launchdaemon if the puppet agent version <4, but not if version > 4.
   I believe this launchdaemon is still required in the new version, or am I wrong?

   In puppet_run.py, the path to the old binary is written:
puppet_cmd = ['/usr/bin/puppet'
   So this file would need some changes as well.

Fuzzycheck

**Comment by grahamgilbert** [comment]
You do not need this at all on Puppet 4. Launch daemons are included in the installer. I may update it to nuke the lock file occasionally, but that's it.
